apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "develop-health.fullname" . }}
  labels:
  {{- include "develop-health.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/load-balancer-type: External
spec:
  ingressClassName: id-app
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "develop-health.fullname" . }}'
            port:
              name: svc-port
        path: /
        pathType: Prefix
