apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop-health
  labels:
    app: develop-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: develop-health
  template:
    metadata:
      labels:
        app: develop-health
    spec:
     # serviceAccountName: "service-a"
      containers:
        - name: develop-health
          image: us-central1-docker.pkg.dev/eappanb4/eb-artifact-registry/develop-health:latest
          ports:
            - name: app-port
              containerPort: 8000
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: develop-health
  namespace: "default"
  labels:
    app: develop-health
spec:
  externalTrafficPolicy: Local
  ports:
  - name: svc-port
    port: 80
    protocol: "TCP"
    targetPort: 8000
  selector:
    app: develop-health
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: develop-health
  annotations:
#    alb.ingress.kubernetes.io/load-balancer-name: develop-health-ingress
    cloud.google.com/load-balancer-type: External

spec:
  ingressClassName: id-app
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: develop-health
                port:
                  name: svc-port
